package org.example.paymentgateway.entities;

public enum WebhookEventType {
    CHARGE_SUCCESS,
    CHARGE_FAILED,
    CHARGE_COMPLETED,
    TRANSFER_SUCCESS,
    TRANSFER_FAILED,
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_DISABLE,
    INVOICE_CREATE,
    INVOICE_UPDATE,
    INVOICE_PAYMENT_FAILED,
    PAYMENT_RECEIVED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    PAYMENT_COMPLETED,
    PAYMENT_PROCESSED,
    PAYMENT_PENDING,
    REFUND_PROCESSED
}
